### PR TITLE
Only install the user script module when it does not exist

### PR DESCRIPTION
**Pull request by icywang86rui**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by icywang86rui** [comment]
I built this change into the MXNet 1.3 container and sent 5 requests to a dummy model with SageMaker local mode. The container is not trying to reinstall anymore.

```
algo-1-j1u9d_1_b286b7a62b39 | [2019-03-22 17:47:33 +0000] [16] [INFO] Starting gunicorn 19.9.0
algo-1-j1u9d_1_b286b7a62b39 | [2019-03-22 17:47:33 +0000] [16] [INFO] Listening at: unix:/tmp/gunicorn.sock (16)
algo-1-j1u9d_1_b286b7a62b39 | [2019-03-22 17:47:33 +0000] [16] [INFO] Using worker: gevent
algo-1-j1u9d_1_b286b7a62b39 | [2019-03-22 17:47:33 +0000] [21] [INFO] Booting worker with pid: 21
algo-1-j1u9d_1_b286b7a62b39 | [2019-03-22 17:47:33 +0000] [22] [INFO] Booting worker with pid: 22
algo-1-j1u9d_1_b286b7a62b39 | 2019-03-22 17:47:36,080 sagemaker-containers INFO     Module dummy_hosting_module does not provide a setup.py.
algo-1-j1u9d_1_b286b7a62b39 | Generating setup.py
algo-1-j1u9d_1_b286b7a62b39 | 2019-03-22 17:47:36,081 sagemaker-containers INFO     Generating setup.cfg
algo-1-j1u9d_1_b286b7a62b39 | 2019-03-22 17:47:36,081 sagemaker-containers INFO     Generating MANIFEST.in
algo-1-j1u9d_1_b286b7a62b39 | 2019-03-22 17:47:36,082 sagemaker-containers INFO     Installing module with the following command:
algo-1-j1u9d_1_b286b7a62b39 | /usr/bin/python -m pip install -U .
algo-1-j1u9d_1_b286b7a62b39 | Processing /opt/ml/code
algo-1-j1u9d_1_b286b7a62b39 | Building wheels for collected packages: dummy-hosting-module
algo-1-j1u9d_1_b286b7a62b39 |   Running setup.py bdist_wheel for dummy-hosting-module ... done
algo-1-j1u9d_1_b286b7a62b39 |   Stored in directory: /tmp/pip-ephem-wheel-cache-tcmx3_t7/wheels/35/24/16/37574d11bf9bde50616c67372a334f94fa8356bc7164af8ca3
algo-1-j1u9d_1_b286b7a62b39 | Successfully built dummy-hosting-module
algo-1-j1u9d_1_b286b7a62b39 | Installing collected packages: dummy-hosting-module
algo-1-j1u9d_1_b286b7a62b39 | Successfully installed dummy-hosting-module-1.0.0
algo-1-j1u9d_1_b286b7a62b39 | You are using pip version 18.1, however version 19.0.3 is available.
algo-1-j1u9d_1_b286b7a62b39 | You should consider upgrading via the 'pip install --upgrade pip' command.
!algo-1-j1u9d_1_b286b7a62b39 | 192.168.0.1 - - [22/Mar/2019:17:47:37 +0000] "GET /ping HTTP/1.1" 200 0 "-" "-"
algo-1-j1u9d_1_b286b7a62b39 | 192.168.0.1 - - [22/Mar/2019:17:47:37 +0000] "POST /invocations HTTP/1.1" 200 22 "-" "-"
algo-1-j1u9d_1_b286b7a62b39 | 192.168.0.1 - - [22/Mar/2019:17:47:37 +0000] "POST /invocations HTTP/1.1" 200 22 "-" "-"
algo-1-j1u9d_1_b286b7a62b39 | 192.168.0.1 - - [22/Mar/2019:17:47:37 +0000] "POST /invocations HTTP/1.1" 200 22 "-" "-"
algo-1-j1u9d_1_b286b7a62b39 | 192.168.0.1 - - [22/Mar/2019:17:47:37 +0000] "POST /invocations HTTP/1.1" 200 22 "-" "-"
```

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://5jg9tp8agh.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=23ceaf3e-55fd-447a-b9a5-98ebfb43193b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by laurenyu** [comment]
changelog entry?

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://5jg9tp8agh.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=bffe899c-d093-4a44-8170-93fa83963cb2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request closed without merging**
